### ISSUE TITLE
Prediction Algorithm: Tokenization Parameters Testing

### ISSUE THREAD

**Issue by lopezjuanma96** [OTTAA-Project/PictogramsPredictionsLibrary#27]
The word tokenization by repetitions method combined with the Viterbi-Markov algorithm seems to be the best option so far for making predicitons, but it needs tweaking of some parameters to get the most out of it, those are:

- [ ] The final score for a path: 

Aside from the transition probability of one word to another (based on dictNgram) and the context score (based on the "context" key of dictNgram), for a better description of those see #17, the viterbi-Markov algorithm gives us new values to consider in the final score: the accumulated transition-emission probability of the wordtypes, the number of "NULL2 wordtype instances, and the length of the predicted sentene. We must find a way to merge them into one sorting paradigm to get the best predictions, for now there already are two, sorting by a value first, other second, then the rest; and a relative vector distance. 

- [x] We could find others and test them on a live server with tweakers that allow interactive modifications of how much this scores matter on the final decision of the best predictions.

- [x] How many repetitions are needed to create a token and it's maximum size:

This might prove to be a much more intense challenge, since changing this two parameters means retraining the model, at least for now. So today the best option is to train a couple of models with variations of this parameters and decide which is best.

- [ ] **For both of them, another option would be to get snippets of the training dataset's sentences and test how good they predict on it, aside from evaluating them on real people using it.**

### Tasks on comments below

- [x] Missing an option to predict the transition only on the largest token

**Comment by lopezjuanma96** [comment]
Up to now the tests have shown that a good token size is 5 words, and a good repetition threshold is 3 (the token must appear more than 3 times, 4 at least), but this is only on the datasets split in 100 sentences. We will carry on tests on the datasets fully loaded (in one file) or in any case in larger sizes, specially the threshold value, which we might have to increase. If so, maybe a ratio of the number of sentences is a better option.

**Comment by lopezjuanma96** [comment]
Although this didn't come from the research associated to this Issue, when developing the API for the Firebase Function on #29, we found out it might be better to add a #TOKENS key inside the dictNgram model where we keep all tokens associated to each word. This association is the word being the last of the token, so for example the tokens "I want candy", "love candy" and "is candy" will be stored on an array with the "candy" key inside the "#TOKENS" key. This way, when facing the last word of a sentence, we don't have to search for every combination of the N last words of the sentences for tokens, just look for the array of that word inside "#TOKENS" and check if any coincides (even faster is this array is sorted by word-length). Since it's kind of a parameter and we are working on this branch right now, we will simplify this fix doing it on this Issue's working branch (test-params)

**Comment by lopezjuanma96** [comment]
For such a big modification as the one mentionded above or others to come, we should add a "#META" key to each dict/hashmap/doc with metadata like date of creation and as many params as we can think of. This is also discussed on #29.

**Comment by lopezjuanma96** [comment]
Corrected some formulas on the gui interface.

- [ ] Missing an option to predict the transition only on the largest token rather than all combinations. If predictions are still good or even better, this would be the option implemented on the Firebase method of #29, to reduce the database queries.

**Comment by lopezjuanma96** [comment]
- [ ] Add minimization: since some firebase query operations take as much as 10 compares (see code), and to reduce storage occupation we could create a minimized version of each model where for example only the 10 most common values of next and context are kept.
